[aws]
disabled = true

[package]
disabled = true

# ORDER
[bun]
disabled = false

[buf]
disabled = false

[cmake]
disabled = false

[cobol]
disabled = false

[crystal]
disabled = false

[daml]
disabled = false

[dart]
disabled = false

[deno]
disabled = false

[dotnet]
disabled = false

[elixir]
disabled = false

[elm]
disabled = false

[erlang]
disabled = false

[fennel]
disabled = false

[gleam]
disabled = false

[golang]
disabled = false

[gradle]
disabled = false

[haxe]
disabled = false

[helm]
disabled = false

[java]
disabled = false

[julia]
disabled = false

[kotlin]
disabled = false

[lua]
disabled = false

[meson]
disabled = false

[nim]
disabled = false

[nodejs]
disabled = false

[ocaml]
disabled = false

[opa]
disabled = false

[perl]
disabled = false

[php]
disabled = false

[pulumi]
disabled = false

[purescript]
disabled = false

[python]
disabled = false

[quarto]
disabled = false

[raku]
disabled = false

[red]
disabled = false

[rlang]
disabled = false

[ruby]
disabled = false

[rust]
disabled = false

[solidity]
disabled = false

[typst]
disabled = false

[swift]
disabled = false

[vagrant]
disabled = false

[vlang]
disabled = false

[zig]
disabled = false
